package com.sourcey.android.customerrorcode;

import lombok.AllArgsConstructor;
import lombok.Getter;

public enum Errors {
    USER_ERROR("001","User errors"),
    USER_EXISTS("002","USER EXISTS"),
    USER_NOT_FOUND("003", "USER NOT FOUND"),
    USER_PASSWORD_NOT_MATCH("004", "PASSWORD NOT MATCH"),
    ERROR_FIELD_MISS("005","FIELD INPUT MISSING"), 
    EMAIL_EXISTS("006", "EMAIL EXISTS"),
    EMAIL_SAME_WITH_OTHER_USERS("007", "EMAIL SAME WITH OTHER USERS"),
    CATEGORY_NOT_FOUND("008", "CATEGORY NOT FOUND"),
    SUBCATEGORY_NOT_FOUND("009", "SUBCATEGORY NOT FOUND"),
    ANSWER_EXIST("010", "ANSWER EXIST"),
    ANSWER_NOT_EXITS("011", "ANSWER NOT EXIST"),
    USERNAME_AND_PASSWORD_IS_NOT_EMPTY("050","USERNAME AND PASSWORD IS NOT EMPTY"),
    NOT_TOKEN("051","NOT TOKEN"),
    TOKEN_NOT_MATCH("052","TOKEN NOT MATCH"),
    ACCESS_DENIED("053","ACCESS DENIED"),
    USER_NOT_ACTIVATED("054","USER NOT ACTIVATED"),
    USER_ACTIVATED("056","USER ACTIVATED"),
    ERROR_SENT_MAIL("080","ERROR SENT MAIL"),
    ACTIVATION_CODE_NOT_MATCH("081","ACTIVATION CODE NOT MATCH"),
    USER_LOCKED("055","USER LOCKED"),
    CANNOT_STORE_FILE("099", "CANNOT COPY FILE"),
    IMAGE_FILE_NOT_SUPPORTED("90", "IMAGE FILE NOT SUPPORTED"),
    IMAGE_FILE_EMPTY("95", "IMAGE FILE CANNOT BE EMPTY"),
    IMAGE_FILE_TOO_LARGE("98", "IMAGE FILE EXCEED 3MB"),
    CANNOT_CREATE_USER_FOLDER("93", "CANNOT CREATE USER FOLDER"),
    ERROR_UPDATE_AVATAR("91", "ERROR UPDATE AVATAR"),
    CANNOT_GET_FILE("92", "CANNOT GET FILE"),
    CANNOT_DELETE_FILE("111", "CANNOT DELETE FILE"),
    IMAGE_FILE_CORRUPTED("70", "IMAGE FILE CORRUPTED"),
    CANNOT_DELETE_YOURSELF("888", "CANNOT DELETE YOURSELF"),
    INVALID_USER_DETAILS("777", "INVALID USER DETAILS"),
    CANNOT_CHANGE_ROLE_ADMIN("666", "CANNOT CHANGE ROLE ADMIN"),
    ROLE_NOT_EXIST("555", "ROLE NOT EXIST"),
    SYSTEM_RESULT_NOT_EXITS("030", "SYSTEM RESULT NOT EXITS" ),
    ANSWER_OR_QUESTION_NOT_EXITS("031", "QUESTION OR ANSWER CODE NOT EXITS"),
    SYSTEM_RESULT_ID_EXIST("032", "SYSTEM ID EXITS"),
    QUESTION_NOT_FOUND("020","QUESTION NOT FOUND"),
    CHANGE_PASS_ERROR("040", "CHANGEPASS ERRORS"),
    NEWPASSWORD_EQUALS_OLDPASSWORD("041", "NEWPASSWORD_EQUALS_OLDPASSWORD"),
    NOT_ANSWER_CORRECT("100", "NOT ANSWER CORRECT"),
    QUESTION_BANK_PRARENT_NOT_EXISTS("101","QUESTION BANK PARENT NOT EXISTS"),
    ADD_QUESTIONS_ERROR("102","ADD QUESTION ERROR"),
    MULTIPLE_EXCEPTION_OCCURS("103","MULIPLE EXCEPTION OCCURS"),
    LESSION_NOT_FOUND("105", "LESSION NOT FOUND"),
    CANNOT_CONVERT_LIST_TO_JSON("106", "CANNOT CONVERT LIST TO JSON"),
    HAS_TO_CHOOSE_SUBCATE("107", "HAS TO CHOOSE SUBCATE"),
    CANNOT_CONVERT_JSON_TO_LIST("108", "CANNOT CONVERT JSON TO LIST"),
    ANSWER_TOO_LESS("104","ANSWER TOO LESS"),
    SUCCESS("200","SUCCESS");


    private String id;
    private String message;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    Errors() {
    }

    Errors(String id, String message) {
        this.id = id;
        this.message = message;
    }

    public String getAdditionalMessage(String additionalMessage) {return message+": "+additionalMessage;}
}
